
version: '3.2'

networks:
    hlf:

services:

    ca_org2:
        networks:
            hlf:
                aliases:
                    - ca_org2
        image: hyperledger/fabric-ca:1.2.0
        hostname: ca.org2.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4c5cf43f7935fcf3d13b950a138e9efe616dae7915a4187764941374f4b6b1b2_sk
        ports:
            - "8054:7054"   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org2:
        image: hyperledger/fabric-couchdb
        hostname: couchdb0_org2
        networks:
           - hlf

    couchdb1_org2:
        image: hyperledger/fabric-couchdb
        hostname: couchdb1_org2
        networks:
           - hlf
