version: '3'
#
networks:
  hlf:

services:
  zookeeper0:
    hostname: zookeeper0.example.com
    image: hyperledger/fabric-zookeeper
    # Give network alias
    networks:
      - hlf
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888

  zookeeper1:
    hostname: zookeeper1.example.com
    environment:
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
      - ZOO_MY_ID=2
    image: hyperledger/fabric-zookeeper
    # Give network alias
    networks:
      - hlf

  zookeeper2:
    hostname: zookeeper2.example.com
    image: hyperledger/fabric-zookeeper
    # Give network alias
    networks:
      - hlf
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
